### ISSUE TITLE
Registry remapping error

### ISSUE THREAD

**Issue by teaheecup** [0rc1nus/Hedgehog-Main-Fabric#4]
Hi! I love your mod. I wasn't sure if this was an issue with the mod itself or something on my end but I wanted to put it here just in case.

![mcFabric-hedgehog-RRerror](https://user-images.githubusercontent.com/99687422/154147344-9d15f6ae-759a-44a0-baf4-0f0b2c7e632d.png)

**Comment by 0rc1nus** [comment]
Should be fixed in the latest version, thanks!
